application: otto-handin-test
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.4"

handlers:
- url: "/css"
  static_dir: "templates/css"
- url: "/js"
  static_dir: "templates/js"
- url: "/img"
  static_dir: "templates/img"

builtins:
- django_wsgi: on

env_variables:
  DJANGO_SETTINGS_MODULE: 'otto_site.settings'
