application: otto-handin-test
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.4"

handlers:
- url: "/css"
  static_dir: "static/css"
- url: "/js"
  static_dir: "static/js"
- url: "/img"
  static_dir: "static/img"
- url: "/fonts"
  static_dir: "static/fonts"
- url: "/upload/"
  script: otto.views.upload_handler

builtins:
- django_wsgi: on

env_variables:
  DJANGO_SETTINGS_MODULE: 'otto_site.settings'
