application: otto
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  static_dir: main.application

libraries:
- name: django
  version: "latest"
  
env_variables:
  DJANGO_SETTINGS_MODULE: 'otto-site.settings'
